### ISSUE TITLE
spotlight fails on long documents

### ISSUE THREAD

**Issue by jgrivolla** [TalnUPF/SpotlightAnnotator#2]
`GET` requests have a limited size (URL length). Need to switch to POST, using `application/x-www-url-form-encoded` for parameters.

Probably just need to change the request at https://github.com/TalnUPF/SpotlightAnnotator/blob/master/src/main/java/org/dbpedia/spotlight/uima/SpotlightAnnotator.java#L169

**Comment by Jibun** [comment]
fixed 84fca2d54bdc4c56fa09ff590e2875762100e016
